#!/usr/bin/env node
// `npx rsc-observer init` — wires the package into a Next.js app idempotently.
//
// What this writes (or appends to, if the file already exists):
//   - instrumentation.ts          → `export { register } from "rsc-observer/instrumentation"`
//   - instrumentation-client.ts   → `import "rsc-observer/instrument-client"`
//
// Instrumentation is enabled automatically in development and is a hard no-op
// in production (NODE_ENV=production) — no marker file, no config changes. Opt
// out in dev by setting RSC_OBSERVER=0.
//
// All steps detect existing wiring and no-op when it's already in place, so the
// command is safe to re-run after an upgrade.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

interface StepResult {
  name: string;
  status: "created" | "updated" | "noop" | "skipped";
  detail?: string;
}

const INSTRUMENTATION_BODY = `// Generated by \`npx rsc-observer init\`. Safe to edit.
export { register } from "rsc-observer/instrumentation";
`;

const INSTRUMENTATION_CLIENT_BODY = `// Generated by \`npx rsc-observer init\`. Safe to edit.
import "rsc-observer/instrument-client";
`;

function findExisting(root: string, basename: string): string | null {
  // Next.js looks for instrumentation files at the project root or under src/.
  // We mirror that — if either exists, treat it as the canonical location.
  const candidates = [".ts", ".tsx", ".js", ".mjs"]
    .flatMap((ext) => [`${basename}${ext}`, `src/${basename}${ext}`])
    .map((rel) => join(root, rel));
  return candidates.find(existsSync) ?? null;
}

function isNextProject(root: string): { ok: boolean; reason?: string } {
  const pkgPath = join(root, "package.json");
  if (!existsSync(pkgPath)) {
    return { ok: false, reason: "no package.json in this directory" };
  }
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (!deps.next) {
      return { ok: false, reason: "next is not a dependency" };
    }
    return { ok: true };
  } catch {
    return { ok: false, reason: "package.json is not valid JSON" };
  }
}

function ensureInstrumentation(root: string): StepResult {
  const existing = findExisting(root, "instrumentation");

  if (!existing) {
    writeFileSync(
      join(root, "instrumentation.ts"),
      INSTRUMENTATION_BODY,
      "utf8",
    );
    return { name: "instrumentation.ts", status: "created" };
  }

  const body = readFileSync(existing, "utf8");
  // Matches both wiring styles: the one-line re-export
  // ("rsc-observer/instrumentation") and the manual composition import
  // ("rsc-observer/instrument-server").
  if (body.includes("rsc-observer/instrument")) {
    return { name: existing, status: "noop", detail: "already wired" };
  }

  // The file already defines the user's own register(). Rather than clobber it
  // with our re-export, compose: import our Node instrumentation inside their
  // register(), guarded to the Node.js runtime (the Edge runtime can't load the
  // http/async_hooks patches).
  const needle = body.match(/(async\s+function\s+register\s*\(\s*\)\s*\{)/);
  if (needle) {
    const insert =
      `\n  if (process.env.NEXT_RUNTIME === "nodejs") {\n` +
      `    await import("rsc-observer/instrument-server");\n` +
      `  }\n`;
    const next = body.replace(needle[1], needle[1] + insert);
    writeFileSync(existing, next, "utf8");
    return { name: existing, status: "updated", detail: "register() patched" };
  }

  return {
    name: existing,
    status: "skipped",
    detail:
      'register() not found — add `export { register } from "rsc-observer/instrumentation"` manually',
  };
}

function ensureInstrumentationClient(root: string): StepResult {
  const existing = findExisting(root, "instrumentation-client");
  const lineMarker = `rsc-observer/instrument-client`;

  if (!existing) {
    writeFileSync(
      join(root, "instrumentation-client.ts"),
      INSTRUMENTATION_CLIENT_BODY,
      "utf8",
    );
    return { name: "instrumentation-client.ts", status: "created" };
  }

  const body = readFileSync(existing, "utf8");
  if (body.includes(lineMarker)) {
    return { name: existing, status: "noop", detail: "already wired" };
  }

  // Prepend the import. Side-effect imports compose safely.
  const next = `import "${lineMarker}";\n` + body;
  writeFileSync(existing, next, "utf8");
  return { name: existing, status: "updated", detail: "import prepended" };
}

function statusIcon(status: StepResult["status"]): string {
  switch (status) {
    case "created":
      return "+";
    case "updated":
      return "~";
    case "noop":
      return "·";
    case "skipped":
      return "!";
  }
}

function printUsage(): void {
  console.log("rsc-observer — dev-time observability for React Server Components");
  console.log("");
  console.log("Usage:");
  console.log("  npx rsc-observer init    Wire the package into the current Next.js app");
  console.log("  npx rsc-observer help    Show this message");
}

function run(): void {
  const cmd = process.argv[2] ?? "help";
  if (cmd === "help" || cmd === "--help" || cmd === "-h") {
    printUsage();
    return;
  }
  if (cmd !== "init") {
    console.error(`rsc-observer: unknown command "${cmd}"`);
    printUsage();
    process.exit(1);
  }

  const root = resolve(process.cwd());
  const gate = isNextProject(root);
  if (!gate.ok) {
    console.error(`rsc-observer init: ${gate.reason}`);
    console.error(`Run from the root of a Next.js project (where package.json lives).`);
    process.exit(1);
  }

  console.log(`rsc-observer init  cwd=${root}`);

  const steps: StepResult[] = [
    ensureInstrumentation(root),
    ensureInstrumentationClient(root),
  ];

  let warned = false;
  for (const s of steps) {
    const detail = s.detail ? ` — ${s.detail}` : "";
    console.log(`  ${statusIcon(s.status)} ${s.name}${detail}`);
    if (s.status === "skipped") warned = true;
  }

  console.log("\nNext steps:");
  console.log("  1. Restart your dev server: pnpm dev (or npm/yarn equivalent)");
  console.log("  2. Open the app — the rsc-observer toggle appears bottom-right");
  console.log("  3. Click it; trigger a request; watch the unified timeline");
  console.log(
    "\nInstrumentation is on automatically in dev and a no-op in production.",
  );
  console.log("Disable it in dev any time with RSC_OBSERVER=0.");

  if (warned) {
    console.log(
      "\nOne or more steps were skipped. See the messages above for manual edits.",
    );
  }
}

run();
