#!/usr/bin/env node
// `npx rsc-observer init` — wires the package into a Next.js app idempotently.
//
// What this writes (or appends to, if the file already exists):
//   - instrumentation.ts          → `await import("rsc-observer/instrument-server")`
//   - instrumentation-client.ts   → `import "rsc-observer/instrument-client"`
//   - middleware.ts               → re-exports `rscObserverMiddleware()`
//   - .rsc-observer               → marker file the dev-gate looks for
//   - .gitignore                  → adds the `.rsc-observer` line
//
// All steps detect existing wiring and no-op when it's already in place, so the
// command is safe to re-run after an upgrade.

import {
  existsSync,
  readFileSync,
  writeFileSync,
  appendFileSync,
} from "node:fs";
import { join, resolve } from "node:path";

interface StepResult {
  name: string;
  status: "created" | "updated" | "noop" | "skipped";
  detail?: string;
}

const MARKER = ".rsc-observer";
const MARKER_BODY =
  "# rsc-observer marker — presence of this file enables dev-mode instrumentation.\n" +
  "# Created by `npx rsc-observer init`. Do not commit.\n";

const INSTRUMENTATION_BODY = `// Generated by \`npx rsc-observer init\`. Safe to edit.
export async function register() {
  if (process.env.NEXT_RUNTIME === "nodejs") {
    await import("rsc-observer/instrument-server");
  }
}
`;

const INSTRUMENTATION_CLIENT_BODY = `// Generated by \`npx rsc-observer init\`. Safe to edit.
import "rsc-observer/instrument-client";
`;

const MIDDLEWARE_BODY = `// Generated by \`npx rsc-observer init\`. Safe to edit.
import { rscObserverMiddleware } from "rsc-observer/middleware";

export default rscObserverMiddleware();

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"],
};
`;

function findExisting(root: string, basename: string): string | null {
  // Next.js looks for instrumentation/middleware at the project root or under
  // src/. We mirror that — if either exists, treat it as the canonical location.
  const candidates = [".ts", ".tsx", ".js", ".mjs"]
    .flatMap((ext) => [`${basename}${ext}`, `src/${basename}${ext}`])
    .map((rel) => join(root, rel));
  return candidates.find(existsSync) ?? null;
}

function isNextProject(root: string): { ok: boolean; reason?: string } {
  const pkgPath = join(root, "package.json");
  if (!existsSync(pkgPath)) {
    return { ok: false, reason: "no package.json in this directory" };
  }
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
    };
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (!deps.next) {
      return { ok: false, reason: "next is not a dependency" };
    }
    return { ok: true };
  } catch {
    return { ok: false, reason: "package.json is not valid JSON" };
  }
}

function ensureInstrumentation(root: string): StepResult {
  const existing = findExisting(root, "instrumentation");
  const importLine = `await import("rsc-observer/instrument-server")`;

  if (!existing) {
    writeFileSync(
      join(root, "instrumentation.ts"),
      INSTRUMENTATION_BODY,
      "utf8",
    );
    return { name: "instrumentation.ts", status: "created" };
  }

  const body = readFileSync(existing, "utf8");
  if (body.includes("rsc-observer/instrument-server")) {
    return { name: existing, status: "noop", detail: "already wired" };
  }

  // Try to inject inside the existing register() function. Simple-minded:
  // inject right after "register() {" or "register() {\n". If we can't find
  // it, leave a clear instruction.
  const needle = body.match(/(async\s+function\s+register\s*\(\s*\)\s*\{)/);
  if (needle) {
    const insert =
      `\n  if (process.env.NEXT_RUNTIME === "nodejs") {\n` +
      `    ${importLine};\n` +
      `  }\n`;
    const next = body.replace(needle[1], needle[1] + insert);
    writeFileSync(existing, next, "utf8");
    return { name: existing, status: "updated", detail: "register() patched" };
  }

  return {
    name: existing,
    status: "skipped",
    detail:
      "register() not found — add `if (process.env.NEXT_RUNTIME === 'nodejs') ${importLine};` manually",
  };
}

function ensureInstrumentationClient(root: string): StepResult {
  const existing = findExisting(root, "instrumentation-client");
  const lineMarker = `rsc-observer/instrument-client`;

  if (!existing) {
    writeFileSync(
      join(root, "instrumentation-client.ts"),
      INSTRUMENTATION_CLIENT_BODY,
      "utf8",
    );
    return { name: "instrumentation-client.ts", status: "created" };
  }

  const body = readFileSync(existing, "utf8");
  if (body.includes(lineMarker)) {
    return { name: existing, status: "noop", detail: "already wired" };
  }

  // Prepend the import. Side-effect imports compose safely.
  const next = `import "${lineMarker}";\n` + body;
  writeFileSync(existing, next, "utf8");
  return { name: existing, status: "updated", detail: "import prepended" };
}

function ensureMiddleware(root: string): StepResult {
  const existing = findExisting(root, "middleware");
  const lineMarker = `rsc-observer/middleware`;

  if (!existing) {
    writeFileSync(join(root, "middleware.ts"), MIDDLEWARE_BODY, "utf8");
    return { name: "middleware.ts", status: "created" };
  }

  const body = readFileSync(existing, "utf8");
  if (body.includes(lineMarker)) {
    return { name: existing, status: "noop", detail: "already wired" };
  }

  return {
    name: existing,
    status: "skipped",
    detail:
      "middleware exists; rsc-observer's middleware composes with yours — see README",
  };
}

function ensureMarker(root: string): StepResult {
  const path = join(root, MARKER);
  if (existsSync(path)) return { name: MARKER, status: "noop" };
  writeFileSync(path, MARKER_BODY, "utf8");
  return { name: MARKER, status: "created" };
}

function ensureGitignore(root: string): StepResult {
  const path = join(root, ".gitignore");
  if (!existsSync(path)) {
    writeFileSync(path, `${MARKER}\n`, "utf8");
    return { name: ".gitignore", status: "created" };
  }
  const body = readFileSync(path, "utf8");
  // Look for the marker as a standalone line (not embedded in another path).
  const lines = body.split(/\r?\n/);
  if (lines.some((l) => l.trim() === MARKER)) {
    return { name: ".gitignore", status: "noop", detail: "already lists marker" };
  }
  const sep = body.endsWith("\n") || body.length === 0 ? "" : "\n";
  appendFileSync(path, `${sep}${MARKER}\n`);
  return { name: ".gitignore", status: "updated" };
}

function statusIcon(status: StepResult["status"]): string {
  switch (status) {
    case "created":
      return "+";
    case "updated":
      return "~";
    case "noop":
      return "·";
    case "skipped":
      return "!";
  }
}

function printUsage(): void {
  console.log("rsc-observer — dev-time observability for React Server Components");
  console.log("");
  console.log("Usage:");
  console.log("  npx rsc-observer init    Wire the package into the current Next.js app");
  console.log("  npx rsc-observer help    Show this message");
}

function run(): void {
  const cmd = process.argv[2] ?? "help";
  if (cmd === "help" || cmd === "--help" || cmd === "-h") {
    printUsage();
    return;
  }
  if (cmd !== "init") {
    console.error(`rsc-observer: unknown command "${cmd}"`);
    printUsage();
    process.exit(1);
  }

  const root = resolve(process.cwd());
  const gate = isNextProject(root);
  if (!gate.ok) {
    console.error(`rsc-observer init: ${gate.reason}`);
    console.error(`Run from the root of a Next.js project (where package.json lives).`);
    process.exit(1);
  }

  console.log(`rsc-observer init  cwd=${root}`);

  const steps: StepResult[] = [
    ensureInstrumentation(root),
    ensureInstrumentationClient(root),
    ensureMiddleware(root),
    ensureMarker(root),
    ensureGitignore(root),
  ];

  let warned = false;
  for (const s of steps) {
    const detail = s.detail ? ` — ${s.detail}` : "";
    console.log(`  ${statusIcon(s.status)} ${s.name}${detail}`);
    if (s.status === "skipped") warned = true;
  }

  console.log("\nNext steps:");
  console.log("  1. Restart your dev server: pnpm dev (or npm/yarn equivalent)");
  console.log("  2. Open the app — the rsc-observer toggle appears bottom-right");
  console.log("  3. Click it; trigger a request; watch the unified timeline");

  if (warned) {
    console.log(
      "\nOne or more steps were skipped. See the messages above for manual edits.",
    );
  }
}

run();
